# Generated by Django 5.0.6 on 2024-06-25 03:23

import backProzone.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='col_departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('funcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='col_roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='env_conductores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.IntegerField(validators=[backProzone.models.validar_edad_minima])),
                ('genero', models.CharField(max_length=10)),
                ('tipo_licencia', models.CharField(choices=[('B', 'B'), ('C', 'C')], max_length=2)),
                ('numero_licencia', models.CharField(max_length=15)),
                ('status', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True)),
            ],
        ),
        migrations.CreateModel(
            name='env_rutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=38)),
                ('destino', models.CharField(max_length=38)),
                ('distancia', models.CharField(max_length=10)),
                ('nombre_ruta', models.CharField(max_length=20)),
                ('status', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True)),
                ('tiempo_estimado', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='env_vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('placas', models.CharField(max_length=10)),
                ('numero_seguro', models.CharField(max_length=20)),
                ('fecha_fabricacion', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True)),
            ],
        ),
        migrations.CreateModel(
            name='pd_clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=20)),
                ('apellido_cliente', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=30)),
                ('status', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True)),
            ],
        ),
        migrations.CreateModel(
            name='prd_Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='prd_categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=50)),
                ('observaciones', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='prd_contacto_proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=35)),
                ('password', models.CharField(max_length=30)),
                ('status', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backProzone.col_departamento')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backProzone.col_roles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='env_envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('observaciones', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('en progreso', 'En Progreso'), ('entregado', 'Entregado')], max_length=15)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backProzone.env_conductores')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backProzone.employee')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backProzone.env_rutas')),
            ],
        ),
        migrations.CreateModel(
            name='env_estado_envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(max_length=50)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
                ('envio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backProzone.env_envio')),
            ],
        ),
        migrations.CreateModel(
            name='pd_pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_pedido', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True)),
                ('calle', models.CharField(max_length=20)),
                ('num_exterior', models.CharField(max_length=5)),
                ('colonia', models.CharField(max_length=20)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backProzone.pd_clientes')),
            ],
        ),
        migrations.CreateModel(
            name='env_historial_envios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_historial', models.CharField(max_length=28)),
                ('observaciones', models.CharField(max_length=50)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
                ('envio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backProzone.env_envio')),
                ('pedido_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backProzone.pd_pedidos')),
            ],
        ),
        migrations.AddField(
            model_name='env_envio',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backProzone.pd_pedidos'),
        ),
        migrations.CreateModel(
            name='prd_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=20)),
                ('descripcion_producto', models.CharField(max_length=50)),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vencimiento_producto', models.DateField(blank=True, null=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backProzone.prd_almacen')),
            ],
        ),
        migrations.CreateModel(
            name='prd_lotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lote', models.CharField(max_length=20)),
                ('descripcion_lote', models.CharField(max_length=50)),
                ('existencia_lote', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_lote', models.DecimalField(decimal_places=2, max_digits=5)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backProzone.prd_almacen')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backProzone.prd_contacto_proveedor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backProzone.prd_producto')),
            ],
        ),
        migrations.CreateModel(
            name='ped_detalles_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=5)),
                ('precio_cantidad_producto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backProzone.pd_pedidos')),
                ('prducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backProzone.prd_producto')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='Sin información', max_length=500)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='Tijuana BC', max_length=30)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backProzone.employee')),
            ],
        ),
        migrations.CreateModel(
            name='env_tipo_vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
                ('refigeracion', models.BooleanField(default=False)),
                ('vehiculo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backProzone.env_vehiculos')),
            ],
            options={
                'db_table': 'env_tipo_vehiculo',
                'unique_together': {('vehiculo_id',)},
            },
        ),
        migrations.CreateModel(
            name='env_conductores_vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(blank=True, null=True)),
                ('fecha_fin_asignacion', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('reparacion', 'Reparacion'), ('baja', 'Baja'), ('uso', 'Uso')], max_length=15)),
                ('conductor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backProzone.env_conductores')),
                ('vehiculo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backProzone.env_vehiculos')),
            ],
            options={
                'db_table': 'env_conductores_vehiculos',
                'unique_together': {('conductor_id', 'vehiculo_id')},
            },
        ),
        migrations.CreateModel(
            name='prd_producto_catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backProzone.prd_categorias')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backProzone.prd_producto')),
            ],
            options={
                'db_table': 'prd_producto_catalogo',
                'unique_together': {('producto', 'categoria')},
            },
        ),
    ]
